#!/usr/bin/env bash
#
# Generate 70 G4DCSmonitor macros (14 base fuels x 5 sources). Each macro
# loads its step-1 ROOT file ONCE, then runs all 4 casks x 6 hexants (24 runs),
# naming each output by (cask, global fuel). All 84*4*5 = 1680 outputs come
# from only 70 (slow) loads.
#
# Usage:  ./generate_macros.sh [output_dir]
#
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_orbit_map.sh"

OUT_DIR="${1:-macros/auto}"
mkdir -p "$OUT_DIR"

BASE_DIR="/bigdata/rimanus/turko46/data/SurfaceFlux"
MEAS_TIME=180   # seconds passed to /dcs-monitor/surf/startRun

SOURCES=(
  "gamma_662keV|gamma-662keV|28|1000000000|1.4e14"
  "gamma_1173keV|gamma-1173keV|22|1000000000|1.0e11"
  "gamma_1332keV|gamma-1332keV|20|1000000000|1.0e11"
  "isotope_Eu154|isotope-Eu154|25|100000000|7.0e10"
  "neutron_Watt|neutron-Watt-a-0p85-b-3p4|6|100000000|4.16e6"
)

BASE_FUELS=(0 1 2 3 5 6 7 8 13 14 15 22 23 32)   # hexant 0
ROTS=(0 60 120 180 240 300)                       # hexants
CASKS=(0 1 2 3)                                    # 4 physical casks

N=0
for BASE in "${BASE_FUELS[@]}"; do
  BASE_PAD="$(printf '%02d' "$BASE")"

  for spec in "${SOURCES[@]}"; do
    IFS='|' read -r SUBDIR TAG NSHELLS NEVTS RATE <<< "$spec"

    SRC_FILE="${BASE_DIR}/${SUBDIR}/data/surface_${TAG}_fuel${BASE}_nShells${NSHELLS}_nEvts${NEVTS}.root"
    if [ ! -f "$SRC_FILE" ]; then echo "[warn] missing: $SRC_FILE" >&2; fi

    MAC="$OUT_DIR/run_baseFuel${BASE_PAD}_${SUBDIR}.mac"

    # ---------- header: geometry built ONCE, all 4 casks at rotation 0 ----------
    cat > "$MAC" <<EOF
# ===================================================================
# Auto-generated by generate_macros.sh -- DO NOT EDIT BY HAND
#   base fuel : ${BASE}   source : ${SUBDIR}
#   Loads the ROOT file ONCE, runs 4 casks x 6 hexants (24 runs).
# ===================================================================

/control/verbose 0
/run/verbose     0
/tracking/verbose 0
/event/verbose   0
/process/verbose 0
/process/em/verbose 0
/process/had/verbose 0

/run/numberOfThreads                128
/dcs-monitor/det/useBiasing         false
/dcs-monitor/det/setBiasingShells   1

# CLYC 
/dcs-monitor/det/setPosition        1350  0  0 mm
/dcs-monitor/det/setRotation        0   -90  0
/dcs-monitor/det/clyc/add

/dcs-monitor/det/clyc/setPbColMaterial G4_Pb
/dcs-monitor/det/clyc/setPbColInnerRadius 15.0 mm
/dcs-monitor/det/clyc/setPbColOuterRadius 35.0 mm
/dcs-monitor/det/clyc/setPbColLength 300.0 mm
/dcs-monitor/det/clyc/setLiFColMaterial LiF
/dcs-monitor/det/clyc/setLiFColInnerRadius 35.0 mm
/dcs-monitor/det/clyc/setLiFColOuterRadius 37.0 mm
/dcs-monitor/det/clyc/setLiFColLength 300.0 mm
/dcs-monitor/det/clyc/setPEColMaterial PEHD_borated
/dcs-monitor/det/clyc/setPEColInnerRadius 37.0 mm
/dcs-monitor/det/clyc/setPEColOuterRadius 300.0 mm
/dcs-monitor/det/clyc/setPEColLength 300.0 mm
/dcs-monitor/det/clyc/setPEPlugMaterial PEHD
/dcs-monitor/det/clyc/setPEPlugLipRadius 300.0 mm
/dcs-monitor/det/clyc/setPEPlugLipLength 10.0 mm
/dcs-monitor/det/clyc/setPEPlugInnerLength 137.5 mm

# CASTOR 440/84 x4 -- ALL at rotation 0 (hexant is applied to the source)
/dcs-monitor/det/setPosition        0 0 0 m
/dcs-monitor/det/setRotation        0 0 0
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition        2.234 2.234 0 m
/dcs-monitor/det/setRotation        0 0 0
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition        2.234 -2.234 0 m
/dcs-monitor/det/setRotation        0 0 0
/dcs-monitor/det/castor440/add
/dcs-monitor/det/setPosition        4.469 0 0 m
/dcs-monitor/det/setRotation        0 0 0
/dcs-monitor/det/castor440/add

/run/initialize
/process/had/rdm/thresholdForVeryLongDecayTime 1e60 year

# source config (set ONCE; ROOT load happens lazily on first startRun)
/dcs-monitor/gun/sourceMode     CASTOR440_surface_from_TTree
/dcs-monitor/surf/sourcePid     0
/dcs-monitor/surf/smearPhi      0.005
/dcs-monitor/surf/smearZ        10.0 mm
/dcs-monitor/surf/smearAngle    0.02
/dcs-monitor/surf/smearEfrac    0.0
/dcs-monitor/surf/numPrimaries  ${NEVTS}
/dcs-monitor/surf/decayRate     ${RATE}
/dcs-monitor/surf/sourceFile    ${SRC_FILE}

/dcs-monitor/run/writePrimary       false
/dcs-monitor/run/writeSurfaceFlux   false
EOF

    # ---------- 24 run blocks: cask x hexant ----------
    for CASK in "${CASKS[@]}"; do
      for ROT in "${ROTS[@]}"; do
        GFUEL="$(lookup_global_fuel "$BASE" "$ROT")"
        GFUEL_PAD="$(printf '%02d' "$GFUEL")"
        ID="cask${CASK}_globalFuel${GFUEL_PAD}_${SUBDIR}"
        cat >> "$MAC" <<EOF

# --- cask=${CASK}  hexant rot=${ROT} deg -> global fuel ${GFUEL} ---
/dcs-monitor/surf/caskNum           ${CASK}
/dcs-monitor/surf/sourceRotZ        ${ROT} deg
/analysis/setFileName               data/clyc_mod3/all_casks/cask${CASK}/detector-response_globalFuel${GFUEL_PAD}_${SUBDIR}
/dcs-monitor/surf/startRun          ${MEAS_TIME} s
EOF
      done
    done

    N=$((N+1))
  done
done

echo "Generated ${N} macros in ${OUT_DIR} (each = 24 runs: 4 casks x 6 hexants)"

