#!/usr/bin/env bash
# =============================================================================
# Run the MuonScint scan matrix generated by macros/generate_muon_matrix.sh.
#
# Each macro in macros/muon/ writes its ROOT file into data_output/ (the path
# is baked into the generated macro by the generator). Per-run logs land in
# data_output/logs/.
#
# Usage:  macros/run_muon_matrix.sh [TIMEOUT_SECONDS]
#         (default TIMEOUT=1800 s per run)
# =============================================================================
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${HERE}/.." && pwd)"
BIN="${ROOT}/build/G4DCSmonitor"
MACDIR="${HERE}/muon"
DATADIR="${ROOT}/data_output"
LOGDIR="${DATADIR}/logs"
TIMEOUT="${1:-1800}"

if [[ ! -x "${BIN}" ]]; then
    echo "ERROR: binary not found: ${BIN}" >&2
    exit 1
fi
mkdir -p "${DATADIR}" "${LOGDIR}"

fail=0
for m in "${MACDIR}"/scan_c?_r?.mac; do
    [[ -e "${m}" ]] || { echo "No macros in ${MACDIR}" >&2; exit 1; }
    b="$(basename "$m" .mac)"
    echo "=== running ${b} ==="
    timeout "${TIMEOUT}" "${BIN}" "$m" > "${LOGDIR}/${b}.log" 2>&1
    rc=$?
    if [[ ${rc} -ne 0 ]]; then
        echo "FAIL ${b} (rc=${rc})"
        fail=$((fail + 1))
    fi
done

echo "Matrix done: $(ls -1 "${DATADIR}"/muon_out_*.root 2>/dev/null | wc -l) ROOT files, ${fail} failures"
